#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env.local}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# The stages below are the demo rehearsal for ticket #17.
# ──────────────────────────────────────────────────────────────────────────
#
# Ticket #17. Run from the repo root:
#   scripts/demo-rehearsal.sh            the full rehearsal (stages 1-6)
# Reads keys from .env.local; set ENV_FILE=<path> to use another file.
#   scripts/demo-rehearsal.sh demo-day   only the warm-up, less than 15 minutes before going on stage

AMITABH="Amitabh Bachchan has died, forward this to everyone"
DHARMENDRA="Dharmendra died"
TRAFFIC="Europe heatwave: it's so hot the traffic lights are melting! Forward to all"

# copy TEXT puts TEXT on the clipboard so the exact same words go in every time
# (the saved answer is found by the exact text, the Claim date, and the exact photo).
copy() {
  if command -v pbcopy >/dev/null 2>&1; then
    printf '%s' "$1" | pbcopy
    printf '  %s✓ copied to clipboard:%s %s\n' "$GREEN" "$RESET" "$1"
  else
    say "Type exactly: $1"
  fi
}

# expect "what you should see" "name" records a surprise instead of stopping.
expect() {
  confirm "Did you see: $1?" || SKIPPED+=("$2 did not give: $1 (tell the agent what you saw)")
}

# run_claims: check both demo Claims on the live site.
run_claims() {
  open_url "$DEMO_URL"
  say "1) The death hoax."
  copy "$AMITABH"
  step "Paste it on the site and press Check. Wait for the answer (about a minute)."
  expect "False" "Amitabh"
  say ""
  say "2) The Dharmendra date flip: the same words, judged on two dates."
  copy "$DHARMENDRA"
  step "Paste it on the site. Open 'More options' and set 'When did you get this?' to 11 Nov 2025."
  step "Press Check and wait."
  expect "False, with 'Judged as of 11 Nov 2025' (his family denied the reports that day)" "Dharmendra as of 11 Nov 2025"
  step "Go back, paste the same words again, and leave the date as today. Press Check."
  expect "True, with 'Judged as of' today's date (he died on 24 Nov 2025)" "Dharmendra as of today"
  say ""
  say "3) The traffic-light photo."
  copy "$TRAFFIC"
  step "Paste the text AND attach the photo: $DEMO_PHOTO"
  step "Press Check and wait."
  expect "Photo check says the photo is real, and the Verdict says False" "Traffic light"
}

DEMO_URL=$(_existing DEMO_URL || true)
DEMO_PHOTO=$(_existing DEMO_PHOTO || true)

if [[ "${1:-}" == "demo-day" ]]; then
  TOTAL_STAGES=1
  banner "Demo day warm-up (#17)"

  stage "Warm up the answers, less than 15 minutes before you present"
  say "Answers about deaths and breaking news are only kept for 15 minutes."
  say "Checking them now means they come back instantly and free on stage."
  say "Do it on the day you present: the saved answer is found by the exact text AND today's date."
  [[ -n "$DEMO_URL" ]] || ask DEMO_URL "Your site's address (https://...vercel.app):"
  [[ -n "$DEMO_PHOTO" ]] || ask DEMO_PHOTO "Where the traffic-light photo is saved on this laptop:"
  say ""
  say "First, make sure Amitabh Bachchan is really alive today."
  open_url "https://news.google.com/search?q=Amitabh%20Bachchan"
  if ! confirm "Latest news says he is alive?"; then
    warn "Then do NOT demo the death hoax: the right answer would now be True."
    SKIPPED+=("Amitabh demo dropped: news says he may have died")
    pause "Press Enter to finish"
    finish; exit 0
  fi
  run_claims
  say ""
  say "On stage, paste the SAME text (and the same photo file): it comes back instantly."
  say "If more than 15 minutes pass before you present, run this again."
  pause "Press Enter to finish"
  finish
  exit 0
fi

TOTAL_STAGES=6
banner "Demo rehearsal (#17)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "OpenAI: stop spending past the budget"
say "If something goes wrong, we want OpenAI to stop, not keep charging."
open_url "https://platform.openai.com/settings/organization/billing/overview"
step "Billing page: make sure auto recharge is OFF. Then the credit you have is the most you can spend."
open_url "https://platform.openai.com/settings/organization/limits"
step "Limits page: set the monthly budget to \$4 (or whatever credit is left)."
note "The page may be laid out a little differently; look for 'Budget' or 'Usage limits'."
confirm "Auto recharge is off and the budget is set?" || SKIPPED+=("OpenAI spend limit")

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Vercel: put the website online"
say "Your keys are copied (not shown) so you can paste them into Vercel in one go."
if command -v pbcopy >/dev/null 2>&1; then
  { grep -E '^(OPENAI_API_KEY|GOOGLE_API_KEY|SERPAPI_API_KEY|UPSTASH_REDIS_REST_URL|UPSTASH_REDIS_REST_TOKEN)=.' "$ENV_FILE" | sed -E 's/="(.*)"$/=\1/'
    echo "OUTSIDE_WORLD_MODE=live"; } | pbcopy
  printf '  %s✓ copied%s the 5 keys from %s + OUTSIDE_WORLD_MODE=live\n' "$GREEN" "$RESET" "$ENV_FILE"
else
  say "Add these one by one from $ENV_FILE: OPENAI_API_KEY, GOOGLE_API_KEY, SERPAPI_API_KEY,"
  say "UPSTASH_REDIS_REST_URL, UPSTASH_REDIS_REST_TOKEN, and OUTSIDE_WORLD_MODE=live"
fi
open_url "https://vercel.com/new"
step "Sign in with GitHub, then Import the repo Souravkumarverma123/TruthAgent."
step "Leave the framework as Next.js."
step "Open 'Environment Variables', click in the first Key box and paste (Cmd+V): all 6 rows fill in."
step "Don't add DEMO_PASS_SECRET: we skip the demo pass."
step "Press Deploy and wait until it says it's ready (a few minutes)."
ask DEMO_URL "Paste your site's address (https://...vercel.app):"
DEMO_URL="${DEMO_URL%/}"
write_env DEMO_URL "$DEMO_URL"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Vercel: is it live, with enough time per Check?"
code=$(curl -s -o /dev/null -w '%{http_code}' "$DEMO_URL" || true)
if [[ "$code" == "200" ]]; then
  printf '  %s✓ the site answers%s (%s)\n' "$GREEN" "$RESET" "$code"
else
  warn "The site answered '$code', not 200. Check the deploy log in Vercel."
  SKIPPED+=("Site didn't answer 200")
fi
step "In Vercel: your project → Settings → Functions → make sure Fluid compute is ON."
note "That gives a Check up to 300 seconds; one takes about 40."
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Get the traffic-light photo"
open_url "https://fullfact.org/environment/video-traffic-light-melting-heatwave-false/"
step "Save one clear frame of the 'melting' traffic light (a screenshot is fine) to this laptop."
note "Use this SAME file every time: the saved answer is found by the exact photo."
ask DEMO_PHOTO "Drag the file into this window (or type its path), then Enter:"
write_env DEMO_PHOTO "$DEMO_PHOTO"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Practice run on the live site"
note "This is practice: these answers only stay saved for about 15 minutes."
note "On demo day, run: scripts/demo-rehearsal.sh demo-day"
note "Only 5 new checks per hour per person, and this uses 4. Pressing Re-check also counts."
run_claims

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Phone and projector"
say "After a Check, the page's address changes to .../check/<id>: that's the proof page."
step "Send that link to your phone (WhatsApp to yourself) and open it."
expect "the proof page is easy to read on the phone, with nothing cut off" "Phone"
step "Plug the laptop into the projector (or share the screen) and open the same page."
step "Stand at the back of the room: can you read the Verdict and the sources?"
note "If it's small, zoom the browser with Cmd and + until it is."
expect "the proof page is readable on the projector" "Projector"

finish
say "Next: tick the boxes on ticket #17 (strike the demo-pass one; we skipped it)."
open_url "https://github.com/Souravkumarverma123/TruthAgent/issues/17"
say "On demo day, run: scripts/demo-rehearsal.sh demo-day"
